### ISSUE TITLE
Sign Up 

### ISSUE THREAD

**Issue by Deerk1ng** [Deerk1ng/crafty-python-project#1]
As a site visitor, I would like to create a new account from any page by clicking a signup button

- [x] New user is registered in the database after request
- [x] Successful response includes new user's `id`, `firstName`, `lastName`, and `email`
- [ ] Error response with status 500 is given when the specified email or username already exists
- [x] Error response with status 400 is given when body validations for the `email`, `firstName`, or `lastName` are violated

**Comment by AlexJc23** [comment]
- [ ]  signup where stuff already exists in db needs status code 500
