### ISSUE TITLE
CREATE a Review based on Product Id

### ISSUE THREAD

**Issue by Deerk1ng** [Deerk1ng/crafty-python-project#11]
POST 'api/products/:productId/reviews'
Create and return a review for a product based on the product's id
- [x] User needs to be authenticated for a successful response
- [x] New Review is added to the database after a successful response
- [x] Review data returned includes `id`, `userId`, `productId`, `itemRating`, `shippingRating`, `description`
- [x] Error response with status 400 is given when body validations for the `itemRating`, `shippingRating`, or `description` are violated
- [x] Error response with status 404 is given when a product does not exist with the provided `id`
- [x] Error response with status 403 is given when a review already exists for the product from the current user

**Comment by w2wewwww** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by AlexJc23** [comment]
_no error response for product doesnt exists - it actually creats a review with product_id_

_no 403 error response for review that already exists - it actually allows me to create many with same user logged in and for same product_id_

**Comment by Deerk1ng** [comment]
submitting a string instead of number results in 500 error. changed reviews form into integerFields which should fix the issue. have not tested in production yet
