### ISSUE TITLE
GET a Product based on Product Id

### ISSUE THREAD

**Issue by Deerk1ng** [Deerk1ng/crafty-python-project#12]
GET `api/products/:productId'
Users should be able to view details of an individual Product.

- [x] Successful response includes every spot in the database
- [x] Product data returned includes `id`, `ownerId`, `name`, `price`, `description`, `category`, `images`, and an `avgRating`
- [x] There is enough seed data in the database to be returned

**Comment by AlexJc23** [comment]
✅  Great
