### ISSUE TITLE
Log in

### ISSUE THREAD

**Issue by Deerk1ng** [Deerk1ng/crafty-python-project#2]
As a site visitor, I want to be able to sign in from any page and become an authenticated user

- [x] Successful response includes User's 'id', `firstName`, `lastName`, and `email`

- [x] Error Response status 401 is given if the credentials are invalid
- [x] Error Response status 400 is given if body validations for 'email', 'firstName',, or 'lastName' are violated

**Comment by AlexJc23** [comment]
works ✅
