### ISSUE TITLE
EDIT a Review

### ISSUE THREAD

**Issue by Deerk1ng** [Deerk1ng/crafty-python-project#23]
PUT 'api/reviews/:reviewId'
Updates and returns an existing Review.
- [x] User needs to be authenticated for a successful response
- [x] Only the owner of the Review is authorized to edit
- [x] Review record is updated in the database after request
- [x] Review data returned includes `id`, `userId`, `productId`, `itemRating`, `shippingRating`, `description`
- [x] Error status 400 is given if a body validation for  `itemRating`, `shippingRating`, or `description` is violated
- [x] Error response with status 404 is given when a review does not exist with the provided `id`

**Comment by AlexJc23** [comment]
### ✅  Good to go
