### ISSUE TITLE
DELETE a Review

### ISSUE THREAD

**Issue by Deerk1ng** [Deerk1ng/crafty-python-project#24]
DELETE 'api/reviews/:reviewId'
Deletes an existing Review.

- [x] User needs to be authenticated for a successful response
- [x] Only the owner of the Review is authorized to delete
- [x] Review is removed from the database after request
- [x] Success response includes a `message` indicating a successful deletion
- [x] Error response with status 404 is given when a review does not exist with
  the provided `id`

**Comment by AlexJc23** [comment]
**Everything checks out**

**Comment by AlexJc23** [comment]
### WORKS ✅
