### ISSUE TITLE
GET all Products

### ISSUE THREAD

**Issue by Deerk1ng** [Deerk1ng/crafty-python-project#5]
GET '/api/products'
Users should be able to view all Products.

- [x] Successful response includes every spot in the database
- [x] Product data returned includes `id`, `ownerId`, `name`, `price`, `description`, `category`, `images`, and an `avgRating`
- [x] Product data returns associated data from Owner including `id`, `shop_name`, 
- [x] There is enough seed data in the database to be returned

**Comment by AlexJc23** [comment]
- [x] Need to add the owner info along with each product

**Comment by AlexJc23** [comment]
✅  Good to go now after edits

**Comment by Deerk1ng** [comment]
if you create a new product but no reviews, the avg.rating tries dividing by zero and causes a timeout. I've fixed in dev but am continuing the production check before attempting a fix
