### ISSUE TITLE
CREATE a Product

### ISSUE THREAD

**Issue by Deerk1ng** [Deerk1ng/crafty-python-project#7]
POST 'api/products'
Users should be able to create a Product.
- [x] User needs to be authenticated for a successful response
- [x] New Product gets added to the database after a successful response 
- [x] Product data returned includes `id`, `ownerId`, `name`, `price`, `description`, `category`
- [x] Error status 400 is given if a body validation for  `name`, `price`, `description`, or `category` is violated

**Comment by AlexJc23** [comment]
### ✅  Works
