### ISSUE TITLE
EDIT a Product

### ISSUE THREAD

**Issue by Deerk1ng** [Deerk1ng/crafty-python-project#8]
PUT 'api/products/:productId'
Updates and returns an existing Product.
- [x] User needs to be authenticated for a successful response
- [x] Only the owner of the Product is authorized to edit
- [x] Product record is updated in the database after request
- [x] Product data returned includes `id`, `ownerId`, `name`, `price`, `description`, `category`
- [x] Error status 400 is given if a body validation for  `name`, `price`, `description`, or `category` is violated
- [x] Error response with status 404 is given when a Product does not exist with the provided `id`

**Comment by AlexJc23** [comment]
###  ✅  Works
