### ISSUE TITLE
DELETE a Product

### ISSUE THREAD

**Issue by Deerk1ng** [Deerk1ng/crafty-python-project#9]
DELETE 'api/products/:productId'
Deletes an existing Product.

- [x] User needs to be authenticated for a successful response
- [x] Only the owner of the product is authorized to delete
- [x] Product is removed from the database after request
- [x] Success response includes a `message` indicating a successful deletion
- [x] Error response with status 404 is given when a product does not exist with
  the provided `id`

**Comment by AlexJc23** [comment]
Perfect ✅
